#!python2.7

import multiprocess as mp
import time

start = time.perf_counter()

def do_sth():
    print("Sleeping 1 sec")
    time.sleep(1)
    print("Done sleeping!")

do_sth()
do_sth()

finish = time.perf_counter()

print(f"Finished in {round(finish-start, 2)} second(s).")